apiVersion: v1
kind: ConfigMap
metadata:
  name: sentra-backend-config
  namespace: sentra
data:
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  LOG_LEVEL: "INFO"
  RELOAD: "false"
  RULES_PATH: "/app/engine/rules/active_threats.yar"
  FRONTEND_URL: "http://sentra-frontend"
