apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentra-frontend
  namespace: sentra
  labels:
    app: sentra-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sentra-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: sentra-frontend
    spec:
      containers:
        - name: frontend
          image: sentra-frontend:latest   # replace with your registry path
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP

          env:
            - name: BACKEND_HOST
              value: "sentra-backend"    # K8s internal DNS → backend Service

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
